'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { GameStore } = require('../server/store')

test('管理员可创建房间、加人、补 100 分并保留审计', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'zhuoji-'))
  const store = new GameStore(path.join(dir, 'store.json'))
  store.ensurePlayer({ id: 'admin', nickname: '房主' })
  const room = store.createRoom({ adminId: 'admin', name: '老友局' })
  store.joinRoom({ roomId: room.id, playerId: 'friend', nickname: '阿杰' })
  const result = store.topUp({ roomId: room.id, operatorId: 'admin', playerId: 'friend' })
  assert.equal(result.player.score, 200)
  assert.equal(store.data.transactions.length, 1)
  assert.throws(() => store.topUp({ roomId: room.id, operatorId: 'friend', playerId: 'friend' }), /管理员/)
  store.joinRoom({ roomId: room.id, playerId: 'watcher', nickname: '观众', role: 'spectator' })
  assert.deepEqual(store.observePlayer({ roomId: room.id, spectatorId: 'watcher', targetPlayerId: 'admin' }), { watchedPlayerIds: ['admin'], muted: false })
  assert.deepEqual(store.observePlayer({ roomId: room.id, spectatorId: 'watcher', targetPlayerId: 'friend' }), { watchedPlayerIds: ['admin', 'friend'], muted: true })
  const round = store.recordRound({ roomId: room.id, summary: { method: 'selfDraw' }, deltas: { admin: 3, friend: -3 } })
  assert.equal(round.number, 1)
  assert.equal(store.data.players.admin.score, 103)
  assert.equal(store.data.players.friend.score, 197)
  store.rollDice({ roomId: room.id, playerId: 'admin', value: 6 })
  assert.equal(store.getRoom(room.id).diceByPlayer.admin, 6)
  store.ensurePlayer({ id: 'friend-2' })
  store.ensurePlayer({ id: 'friend-3' })
  store.getRoom(room.id).seats.push({ playerId: 'friend-2' }, { playerId: 'friend-3' })
  store.beginRound({ roomId: room.id, randomChickenKey: 'tong-3', chickenBoost: 1 })
  assert.equal(store.getRoom(room.id).status, 'PLAYING')
  assert.equal(store.getRoom(room.id).randomChickenStreak, 1)
  const penalty = store.recordAdjustment({ roomId: room.id, summary: { type: 'falsePong' }, deltas: { admin: -1 } })
  assert.equal(penalty.type, 'SCORE_ADJUSTMENT')
  assert.equal(store.data.players.admin.score, 102)
  assert.equal(store.getRoom(room.id).roundNumber, 1)
  fs.rmSync(dir, { recursive: true, force: true })
})
